# Generated by Django 4.2.14 on 2024-07-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_hired', models.DateField()),
                ('now_shop', models.CharField(max_length=100)),
                ('shops', models.IntegerField()),
                ('way_shops', models.IntegerField()),
                ('move_shops', models.IntegerField()),
            ],
        ),
    ]
