# Generated by Django 4.2.14 on 2024-07-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisor',
            name='photo',
            field=models.ImageField(default='img/profile.png', upload_to=''),
        ),
    ]
