# Generated by Django 4.2.14 on 2024-07-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_revisor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisor',
            name='photo',
        ),
    ]
