# Generated by Django 4.2.14 on 2024-07-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shop_alter_revisor_now_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisor',
            name='now_shop',
            field=models.CharField(max_length=100),
        ),
    ]
