# Generated by Django 4.2.14 on 2024-07-24 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_revisor_now_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='last_counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_counted_shops', to='main.revisor'),
        ),
    ]
