# Generated by Django 4.2.14 on 2024-07-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_shop_last_counted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='shop',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
