# Generated by Django 4.2.14 on 2024-08-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_shop_options_shop_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisor',
            name='now_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shop'),
        ),
    ]
