# Generated by Django 4.2.14 on 2024-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_revisor_now_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('transported', 'Transported'), ('c1', 'C1'), ('away', 'Away'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
