# Generated by Django 4.2.14 on 2024-08-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='last_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='main.task'),
        ),
    ]
