# Generated by Django 4.2.14 on 2024-08-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_shop_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='last_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
