# Generated by Django 4.2.14 on 2024-08-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_revisor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisor',
            name='user',
        ),
    ]
