# Generated by Django 4.2.14 on 2024-08-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_revisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisor',
            name='date_hired',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
