# Generated by Django 4.2.14 on 2024-08-21 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_remove_revisor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
