# Generated by Django 4.2.14 on 2024-08-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_revisor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='last_revision',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
