# Generated by Django 4.2.14 on 2024-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_shop_last_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='minus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='plus',
            field=models.IntegerField(default=0),
        ),
    ]
