# Generated by Django 4.2.14 on 2024-08-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_task_minus_task_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='last_revision',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
