# Generated by Django 4.2.14 on 2024-08-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_shop_last_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='plus_or_minus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
