# Generated by Django 4.2.14 on 2024-08-29 18:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_shop_plus_or_minus_revisor_plus_or_minus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisor',
            name='plus_or_minus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
