# Generated by Django 4.2.14 on 2024-09-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_revisor_plus_or_minus'),
        ('main', '0031_alter_revisor_plus_or_minus'),
    ]

    operations = [
    ]
