# Generated by Django 4.2.14 on 2024-09-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_shop_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='avg_personal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='avg_purity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='avg_sorting',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
