# Generated by Django 4.2.14 on 2024-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_shop_avg_personal_shop_avg_purity_shop_avg_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='last_revision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
