# Generated by Django 4.2.14 on 2024-09-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_shop_last_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisor',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='revisor',
            name='favourite_shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_shop', to='main.shop'),
        ),
    ]
