# Generated by Django 4.2.14 on 2024-09-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_revisor_favourite_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
