# Generated by Django 4.2.14 on 2024-09-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_revisor_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisor',
            name='profile_picture',
        ),
    ]
