# Generated by Django 4.2.14 on 2024-10-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_revisor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisor',
            name='who_are',
            field=models.CharField(choices=[('revisor', 'Revisor'), ('intern', 'Intern')], default='revisor', max_length=20),
        ),
    ]
