# Generated by Django 4.2.14 on 2024-10-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_revisor_who_are'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisor',
            name='who_are',
            field=models.CharField(choices=[('ревізор', 'Ревізор'), ('стажер', 'Стажер')], default='Ревізор', max_length=20),
        ),
    ]
