# Generated by Django 4.2.14 on 2024-10-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_shop_photo_shop_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='video',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.shop')),
            ],
        ),
    ]
