# Generated by Django 4.2.14 on 2024-12-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_shop_photo_remove_shop_video_video_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisor',
            name='plus_or_minus',
        ),
    ]
