# Generated by Django 4.2.14 on 2024-08-17 23:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0015_alter_revisor_move_shops_alter_revisor_shops_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.revisor')),
            ],
            options={
                'unique_together': {('revisor', 'date')},
            },
        ),
    ]
