# Generated by Django 4.2.14 on 2024-08-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
