# Generated by Django 4.2.14 on 2024-08-25 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counting', '0003_alter_worklog_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='revisor',
        ),
        migrations.AddField(
            model_name='worklog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
