# Generated by Django 4.2.14 on 2024-10-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0004_remove_worklog_revisor_worklog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='bonus_minutes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
