# Generated by Django 4.2.14 on 2025-01-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0007_alter_worklog_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='bonus_minutes',
        ),
    ]
