# Generated by Django 4.2.14 on 2025-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0009_worklog_bonus_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='was_on_far_point',
            field=models.BooleanField(default=False),
        ),
    ]
