# Generated by Django 4.2.14 on 2024-12-14 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hours_bonus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus_hours',
            name='year',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bonus_hours',
            unique_together={('user', 'month', 'year')},
        ),
    ]
