# Generated by Django 4.2.14 on 2024-12-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_bonus', '0003_bonus_hours_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus_hours',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
