# Generated by Django 4.2.14 on 2025-01-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours_bonus', '0004_alter_bonus_hours_minutes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bonus_hours',
            unique_together=set(),
        ),
    ]
